version: '3'

volumes:
  standalone_data:

services:
  postgres94:
    container_name: postgres94
    hostname: postgres94
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - standalone_data:/var/lib/postgresql/data
      - /Users/alejandrolopez/share/postgresql:/mnt/share
    environment:
      POSTGRES_PASSWORD: dellanera
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
