version: '3'

volumes:
  standalone_data:

services:
  postgres94:
    container_name: postgres94
    hostname: postgres94
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - standalone_data:/var/lib/postgresql/data
      - /Users/alejandrolopez/share/postgresql:/mnt/share
    environment:
      POSTGRES_PASSWORD: dellanera
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    links:
      - postgres94
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080