version: '3'

volumes:
  standalone_data:

services:
  mongodb24:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - standalone_data:/data/db
      - /data/db:/data/db
      - /Users/alejandrolopez/Proyectos/dockers/share:/mnt/share
    ports:
        - 27017:27017
