version: '3'

volumes:
  standalone_data:

services:
  mongo24:
    container_name: mongo24
    hostname: mongo24
    image: mongo:2.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - standalone_data:/data/db
      - /Users/alejandrolopez/share/mongodb:/mnt/share
    ports:
        - 27017:27017
