version: "3"
services:
  api:
    container_name: api
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./api/hello-world:/usr/src/app
    ports:
      - "8081:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8080:8080
    volumes:
      - ./client/hello-world:/data
    environment:
      - API_URL=http://localhost:8081/
    links:
      - api

  # express:
  #   container_name: express
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.express
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /Users/alejandrolopez/Proyectos/Express:/usr/src/app
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./db:/data/db
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   volumes:
  #     - ./express.conf:/etc/nginx/conf.d/default.conf
  #     - /Users/alejandrolopez/Proyectos/Vue:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   links:
  #     - express
