version: '3'

volumes:
  standalone_data:

services:
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - standalone_data:/var/lib/mysql
      - /Users/alejandrolopez/share/mysql:/mnt/share
    environment:
      MYSQL_ROOT_PASSWORD: dellanera
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
