version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: D3ll4n3r4
      MSSQL_PID: Developer
    ports:
      - '1433:1433'
    volumes:
      - ms-sqlserver-data:/var/opt/mssql
  adminer:
    image: clue/adminer
    restart: always
    ports:
      - 8080:80

volumes:
  ms-sqlserver-data:
    driver: local
