version: '3'

volumes:
  standalone_data:

services:
  postgres965:
    container_name: postgres965
    hostname: postgres965
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    volumes:
      - standalone_data:/var/lib/postgresql/data
      - /Users/iquesada/docker/share:/mnt/share
    environment:
      POSTGRES_PASSWORD: dellanera
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
