version: '3'

volumes:
  standalone_data:

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - standalone_data:/var/lib/postgresql/data
      - /Users/alejandrolopez/share/postgresql:/mnt/share
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dellanera
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
