version: '3'

volumes:
  standalone_data:

services:
  mysql:
    container_name: mysql55
    hostname: mysql55
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - standalone_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dellanera
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
